Repository JapaneseEducateService/backend, pull requests merged in 2024-04, with the labels that each got.

#65 🔨 Refactor : manager, user table 병합 작업 및 ..
  app/Helper/Helpers.php
  app/Http/Controllers/AuthController.php
  app/Models/JlptQuestion.php
  app/Models/Manager.php
  app/Models/User.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2024_02_28_060159_create_managers_table.php
  database/migrations/2024_02_28_060812_create_jlpt_questions_table.php
  routes/api.php
Labels: 🔨 Refactor

#67 ✨ feat : 발음평가 구현, 🔨 Refactor: laravel mecab 삭제
  app/Helper/Helpers.php
  app/Http/Controllers/ManagerController.php
  app/Http/Controllers/SpeechController.php
  composer.json
  composer.lock
  docker/8.0/Dockerfile
  docker/8.0/php.ini
  docker/8.0/start-container
  docker/8.0/supervisord.conf
  docker/8.1/Dockerfile
  docker/8.1/php.ini
  docker/8.1/start-container
  docker/8.1/supervisord.conf
  docker/8.2/Dockerfile
  docker/8.2/php.ini
  docker/8.2/start-container
  docker/8.2/supervisord.conf
  docker/8.3/Dockerfile
  docker/8.3/php.ini
  docker/8.3/start-container
  docker/8.3/supervisord.conf
  docker/pgsql/create-testing-database.sql
  routes/api.php
Labels: ✨ Feature, 🔨 Refactor

#70 ✨ Feature : level의 더미데이터 작성 및 ...
  app/Helper/Helpers.php
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/SpeechController.php
  app/Http/Controllers/VocabularyNoteController.php
  app/Models/VocabularyNote.php
  composer.lock
  database/migrations/2024_02_21_060733_create_levels_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/LevelSeeder.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feature, 🔨 Refactor

#71 🔨 Refactor : 점수 관련 DB 수정
  app/Enums/CategoryEnum.php
  app/Models/Score.php
  database/migrations/2024_02_29_070217_create_rankings_table.php
  database/migrations/2024_02_29_070217_create_scores_table.php
  database/seeders/LevelSeeder.php
Labels: 🔨 Refactor

#73 ✨ feat : public 단어장 목록 반환 구현, 🐞 BugFix : worldOfWords 결과 저장 에러 수정
  app/Http/Controllers/CardController.php
  app/Http/Controllers/GameController.php
  app/Http/Controllers/VocabularyNoteController.php
  app/Http/Controllers/WordOfWorldController.php
  app/Models/VocabularyNote.php
  database/migrations/2024_02_22_052255_create_vocabulary_notes_table.php
  database/seeders/SentenceSeeder.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐞 BugFix, ✨ Feature

#75 🔨 Refactor : Enums 분리 작업 및 분리에 따른 모델 및 마이그레이션 수정
  app/Enums/GrammarLevelEnum.php
  app/Enums/LevelEnum.php
  app/Enums/RoleEnum.php
  app/Models/Grammar.php
  app/Models/Level.php
  app/Models/User.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2024_02_21_060733_create_levels_table.php
  database/migrations/2024_02_29_070217_create_scores_table.php
  database/migrations/2024_03_25_083445_create_grammars_table.php
  database/migrations/2024_04_03_102710_create_user_grammar_examples_table.php
Labels: 🔨 Refactor

#76 🔨 Refactor : GameController.php 파일에서 WordOfWorldController 클래스를 GameC…
  app/Http/Controllers/GameController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🔨 Refactor

#78 🔨 Refactor : ReviewNote 모델 삭제 및 관련 파일 수정
  app/Http/Controllers/GameController.php
  app/Http/Controllers/VocabularyNoteController.php
  app/Models/ReviewNote.php
  app/Models/User.php
  app/Models/VocabularyNote.php
  database/migrations/2024_02_29_071744_create_review_notes_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🔨 Refactor

#81 ✨ Feature : Vocabulary Seeder 작성 외 1개 작업
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/VocabularyNoteController.php
  database/seeders/AdminSeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/VocabularySeeder.php
Labels: ✨ Feature, 🔨 Refactor

#82 🔨 Refactor : S3 작업중 ... 중간 점검 전 최신화
  app/Helper/Helpers.php
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/RankingController.php
  app/Http/Controllers/S3Controller.php
  app/Http/Controllers/TypingPracticeController.php
  app/Models/Level.php
  app/Models/Score.php
  app/OpenApi/Parameters/S3Parameters.php
  app/OpenApi/RequestBodies/S3RequestBody.php
  app/OpenApi/RequestBodies/SentenceRequestBody.php
  app/OpenApi/Schemas/S3Schema.php
  composer.json
  composer.lock
  config/openapi.php
  config/sanctum.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feature, 🔨 Refactor

#85 🔨 Refactor : 문법db 수정에 따른 변경사항
  app/Models/Grammar.php
  app/Models/GrammarExample.php
  app/Models/User.php
  database/migrations/2024_04_15_123603_create_grammar_examples_table.php
  routes/api.php
Labels: 🔨 Refactor

#86 🔨 Refactor : 문법 테이블의 컬럼명 변경 및 관계 수정
  database/migrations/2024_03_25_083445_create_grammars_table.php
  database/migrations/2024_04_03_102710_create_user_grammar_examples_table.php
Labels: 🔨 Refactor

#88 🔨 Refactor : 데이터베이스 시더 수정, 모델수정
  app/Models/Grammar.php
  app/Models/JlptQuestion.php
  app/Models/Level.php
  app/Models/VocabularyNote.php
  database/seeders/AdminSeeder.php
  database/seeders/VocabularySeeder.php
Labels: 🔨 Refactor

#89 ✨ Feature : S3관련 Helper 함수 생성 외 1개 작업
  app/Helper/Helpers.php
  database/seeders/AdminSeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/GrammarSeeder.php
  database/seeders/ScoreSeeder.php
  database/seeders/SentenceSeeder.php
  database/seeders/UserSeeder.php
  database/seeders/VocabularySeeder.php
Labels: ✨ Feature, 🔨 Refactor

#91 🔨 Refactor : testToken seeder로 변경
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/SpeechController.php
  app/Http/Controllers/VocabularyNoteController.php
  database/seeders/TestSeeder.php
  routes/api.php
Labels: 🔨 Refactor

#93 ✨ feat : GoogleTTS 구현
  app/Http/Controllers/SpeechController.php
  app/OpenApi/RequestBodies/TTSRequestBody.php
  app/OpenApi/Schemas/TTSSchema.php
  storage/api-docs/api-docs.json
Labels: ✨ Feature

#94 🔨 Refactor : grammar 카테고리 조회 -> 전체 조회 변경
  app/Enums/GrammarLevelEnum.php
  app/Http/Controllers/GrammarController.php
  app/Models/Grammar.php
  app/Models/GrammarExample.php
Labels: 🔨 Refactor

#96 ✨ Feature : 레벨별 단어장 리턴, 🐞 BugFix : user_id가 아닌 user 정보 리턴
  app/Http/Controllers/GrammarController.php
  app/Http/Controllers/VocabularyNoteController.php
  app/Models/VocabularyNote.php
  app/OpenApi/Parameters/DeleteSentenceParameters.php
  app/OpenApi/Parameters/VocabularyLevelParameters.php
  app/OpenApi/Schemas/TTSSchema.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐞 BugFix, ✨ Feature

#99 🐞 BugFix : seeder로 생성된 단어장 오류 해결, 관리자 단어장 이외의 단어장도 함께 리턴 문제 해결
  app/Http/Controllers/VocabularyNoteController.php
  database/seeders/VocabularySeeder.php
Labels: 🐞 BugFix

#100 🐞 BugFix : seeder로 생성된 단어장 오류 해결, 관리자 단어장 이외의 단어장도 함께 리턴 문제 해결
  app/Http/Controllers/VocabularyNoteController.php
  database/seeders/VocabularySeeder.php
Labels: 🐞 BugFix
