Repository JapaneseEducateService/backend, pull requests merged in 2024-02, with the labels that each got.

#4 ✨ feat : social login 기능 구현
  app/Http/Controllers/SocialController.php
  app/Models/SocialAccount.php
  app/Models/User.php
  app/Providers/EventServiceProvider.php
  composer.json
  composer.lock
  config/app.php
  config/app_frontend.php
  config/services.php
  database/migrations/2024_02_20_082356_create_social_accounts_table.php
  resources/views/welcome.blade.php
  routes/api.php
  routes/web.php
Labels: ✨ Feature

#7 ⚙ Setting: API swagger annotation 적용
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/Controller.php
  app/Http/Controllers/SocialController.php
  composer.json
  composer.lock
  config/app.php
  config/l5-swagger.php
  package-lock.json
  resources/views/vendor/l5-swagger/.gitkeep
  resources/views/vendor/l5-swagger/index.blade.php
  storage/api-docs/api-docs.json
Labels: ⚙ Setting

#16 token refresh 기능 구현 및 만료된 token scheduling 기능 구현
  app/Console/Kernel.php
  app/Http/Controllers/AuthController.php
  composer.lock
Labels: ✨ Feature, 🔨 Refactor

#18 회원탈퇴, 만료된 액세스토큰 스케줄러 수정 및 ...
  app/Console/Kernel.php
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/ImageTranslationController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feature, 📃 Docs, 🔨 Refactor

#19 🔨 chore : 회원가입시 validator 수정및 swagger API 명세서 작성 및 수정
  app/Console/Kernel.php
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/ImageTranslationController.php
  app/Http/Controllers/MailController.php
  app/Mail/RegisterEmail.php
  app/Models/User.php
  composer.json
  composer.lock
  config/app.php
  database/migrations/2014_10_12_000000_create_users_table.php
  resources/views/mail/register-email.blade.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐞 BugFix, 📃 Docs, 🔨 Refactor, ✅ Test

#21 register, login 로직 수정, 아이디 사용 -> 이메일 사용 변경
  app/Http/Controllers/AuthController.php
  app/Models/User.php
  config/sanctum.php
  database/migrations/2014_10_12_000000_create_users_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🔨 Refactor
