Repository JapaneseEducateService/backend, pull requests merged in 2024-06, with the labels that each got.

#124 🐞 BugFix : 스웨거 작성 오류
  app/Http/Controllers/VocabularyNoteController.php
  app/OpenApi/Parameters/VocabularyLevelParameters.php
  database/migrations/2024_03_05_013650_create_sentence_notes_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐞 BugFix

#125 🐞 BugFix : 스웨거 작성 오류
  app/Http/Controllers/VocabularyNoteController.php
  app/OpenApi/Parameters/VocabularyLevelParameters.php
  database/migrations/2024_03_05_013650_create_sentence_notes_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐞 BugFix

#127 🔨 Refactor : csrf-cookie route 명시적 설정 테스트
  app/Http/Controllers/SentenceNoteController.php
  app/Http/Kernel.php
  composer.lock
  config/cors.php
  config/session.php
  routes/api.php
Labels: 🔨 Refactor

#128 🔨 Refactor : csrf-cookie route 명시적 설정 테스트
  app/Http/Controllers/SentenceNoteController.php
  app/Http/Kernel.php
  composer.lock
  config/cors.php
  config/session.php
  routes/api.php
Labels: 🔨 Refactor

#129 🔨 Refactor : cors test
  app/Http/Kernel.php
Labels: 🐞 BugFix

#130 🔨 Refactor : cors 에러 수정 테스트
  app/Http/Controllers/VocabularyNoteController.php
  database/migrations/2024_03_05_013650_create_sentence_notes_table.php
  nginx/default.conf
Labels: 🔨 Refactor

#131 🔨 Refactor : cors 에러 수정 테스트
  app/Http/Controllers/VocabularyNoteController.php
  database/migrations/2024_03_05_013650_create_sentence_notes_table.php
  nginx/default.conf
Labels: 🌏 Deploy

#132 🔨 Refactor : cors 에러 수정 테스트
  app/Http/Middleware/VerifyCsrfToken.php
Labels: 🔨 Refactor
