Repository JapaneseEducateService/backend, pull requests merged in 2024-05, with the labels that each got.

#101 🌏 Deploy : Laravel 배포전 수정
  Dockerfile
  Dockerfile.nginx
  artisan
  docker-compose.yml
Labels: 🌏 Deploy

#102 🌏 Deploy : Laravel 배포전 수정
  Dockerfile
Labels: 🌏 Deploy

#103 🌏 Deploy : Laravel 배포전 수정
  Dockerfile
Labels: 🌏 Deploy

#104 🌏 Deploy : Laravel 배포전 수정
  Dockerfile
Labels: 🌏 Deploy

#105 🌏 Deploy : Laravel 배포전 수정
  Dockerfile
  app/Http/Responses/MyCustomMediaType.php
  app/Http/Responses/MyCustomSchema.php
  app/OpenApi/RequestBodies/ImageRequestBody.php
  app/OpenApi/RequestBodies/PronunciationResultRequestBody.php
  app/OpenApi/RequestBodies/StoreExcelVocaRequestBody.php
  app/OpenApi/RequestBodies/StoreGrammarRequestBody.php
  app/OpenApi/RequestBodies/StoreSentencesRequestBody.php
  app/OpenApi/RequestBodies/StoreVocabularyNotesRequestBody.php
  app/OpenApi/RequestBodies/UpdateVocabularyNotesRequestBody.php
  app/OpenApi/Schemas/ExcelSchema.php
  app/OpenApi/Schemas/ImageSchema.php
  app/OpenApi/Schemas/PronunciationResultSchema.php
  app/OpenApi/Schemas/StoreGrammarSchema.php
  app/OpenApi/Schemas/TTSSchema.php
  app/OpenApi/Schemas/TxtFileSchema.php
  storage/api-docs/api-docs.json
Labels: 🌏 Deploy

#106 🌏 Deploy : Laravel 배포전 수정
  nginx/default.conf
Labels: 🌏 Deploy

#107 🌏 Deploy : Laravel 배포전 수정
  nginx/default.conf
Labels: 🌏 Deploy

#108 🌏 Deploy : Laravel 배포전 수정
  nginx/default.conf
Labels: 🌏 Deploy

#109 🌏 Deploy : Laravel 배포전 수정
  Dockerfile
Labels: 🌏 Deploy

#110 🌏 Deploy : Laravel 1.0.0 relese
  .github/ISSUE_TEMPLATE/✨-feature.md
  .github/workflows/main.yml
  Dockerfile
  Dockerfile.nginx
  app/Http/Responses/MyCustomMediaType.php
  app/Http/Responses/MyCustomSchema.php
  app/OpenApi/RequestBodies/ImageRequestBody.php
  app/OpenApi/RequestBodies/PronunciationResultRequestBody.php
  app/OpenApi/RequestBodies/StoreExcelVocaRequestBody.php
  app/OpenApi/RequestBodies/StoreGrammarRequestBody.php
  app/OpenApi/RequestBodies/StoreSentencesRequestBody.php
  app/OpenApi/RequestBodies/StoreVocabularyNotesRequestBody.php
  app/OpenApi/RequestBodies/UpdateVocabularyNotesRequestBody.php
  app/OpenApi/Schemas/ExcelSchema.php
  app/OpenApi/Schemas/ImageSchema.php
  app/OpenApi/Schemas/PronunciationResultSchema.php
  app/OpenApi/Schemas/StoreGrammarSchema.php
  app/OpenApi/Schemas/TTSSchema.php
  app/OpenApi/Schemas/TxtFileSchema.php
  artisan
  docker-compose.yml
  nginx/default.conf
  storage/api-docs/api-docs.json
Labels: 🌏 Deploy

#111 🌏 Deploy : flask 요청 주소 수정
  app/Http/Controllers/GameController.php
  app/Http/Controllers/SpeechController.php
  app/Http/Controllers/VocabularyNoteController.php
  routes/api.php
Labels: 🌏 Deploy

#112 🌏 Deploy : Laravel release 1.0.1
  app/Http/Controllers/GameController.php
  app/Http/Controllers/SpeechController.php
  app/Http/Controllers/VocabularyNoteController.php
  routes/api.php
Labels: 🌏 Deploy

#114 ✨ feat : 노트 복사 기능 구현
  app/Http/Controllers/VocabularyNoteController.php
  app/OpenApi/Parameters/VocabularyLevelParameters.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feature

#116 🔨 Refactor : sentence->sentenceNote로 변경 작업 진행 및 CRUD 구현
  app/Helper/Helpers.php
  app/Http/Controllers/SentenceNoteController.php
  app/Http/Controllers/SocialController.php
  app/Http/Controllers/TypingPracticeController.php
  app/Http/Controllers/VocabularyNoteController.php
  app/Models/SentenceNote.php
  app/OpenApi/RequestBodies/StoreSentenceNotesRequestBody.php
  app/OpenApi/RequestBodies/UpdateSentenceNoteRequestBody.php
  app/OpenApi/Schemas/SentenceNoteSchema.php
  app/OpenApi/Schemas/UpdateSentenceNoteSchema.php
  config/openapi.php
  database/migrations/2024_03_05_013650_create_sentence_notes_table.php
  database/migrations/2024_03_05_013650_create_sentences_table.php
  database/seeders/SentenceSeeder.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🔨 Refactor

#117 🔨 Refactor : sentence->sentenceNote로 변경 작업 진행 및 CRUD 구현
  app/Helper/Helpers.php
  app/Http/Controllers/SentenceNoteController.php
  app/Http/Controllers/SocialController.php
  app/Http/Controllers/TypingPracticeController.php
  app/Http/Controllers/VocabularyNoteController.php
  app/Models/SentenceNote.php
  app/OpenApi/RequestBodies/StoreSentenceNotesRequestBody.php
  app/OpenApi/RequestBodies/UpdateSentenceNoteRequestBody.php
  app/OpenApi/Schemas/SentenceNoteSchema.php
  app/OpenApi/Schemas/UpdateSentenceNoteSchema.php
  config/openapi.php
  database/migrations/2024_03_05_013650_create_sentence_notes_table.php
  database/migrations/2024_03_05_013650_create_sentences_table.php
  database/seeders/SentenceSeeder.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🔨 Refactor

#122 🔨 Refactor : swagger error fix... and feat: create sentence_notes OCR
  app/Helper/Helpers.php
  app/Http/Controllers/SentenceNoteController.php
  app/Models/User.php
  database/migrations/2024_03_05_013650_create_sentence_notes_table.php
  database/seeders/SentenceSeeder.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#123 🌏 Deploy : release v1.1.0
  app/Helper/Helpers.php
  app/Http/Controllers/SentenceNoteController.php
  app/Models/User.php
  database/migrations/2024_03_05_013650_create_sentence_notes_table.php
  database/seeders/SentenceSeeder.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🌏 Deploy
