Repository JapaneseEducateService/backend, pull requests merged in 2024-03, with the labels that each got.

#27 🐞 BugFix : 소셜 로그인 redirect 오류 수정
  app/Http/Controllers/SocialController.php
  app/Http/Controllers/WordOfWorldController.php
  database/migrations/2024_02_29_070154_create_categories_table.php
  database/migrations/2024_02_29_070217_create_rankings_table.php
  database/migrations/2024_02_29_071744_create_review_notes_table.php
Labels: 🐞 BugFix

#28 🔨 chore : ocr관련 사용자helper함수 생성 및 helper함수 composer.json 적용
  app/Helper/Helpers.php
  app/Http/Controllers/ImageTranslationController.php
  composer.json
  routes/api.php
Labels: 🔨 Refactor

#30 ✨ feat : 타자연습을 위한 문장 만드는 기능 구현 80% 및 마이그레이션 작업중
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/TypingPracticeController.php
  app/Models/Setences.php
  database/migrations/2024_03_05_013650_create_sentences_table.php
  routes/api.php
Labels: ✨ Feature, 🔨 Refactor

#35 🔨 chore : migration file 수정, ✨ feat : social login mobile 기능 구현
  app/Http/Controllers/SocialController.php
  app/Http/Controllers/VocabularyNoteController.php
  app/Imports/VocabularyNoteImport.php
  app/Models/VocabularyNote.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2024_02_20_082356_create_social_accounts_table.php
  database/migrations/2024_02_22_052255_create_vocabulary_notes_table.php
  database/migrations/2024_02_28_060159_create_managers_table.php
  database/migrations/2024_02_28_060733_create_levels_table.php
  database/migrations/2024_02_28_060812_create_jlpt_questions_table.php
  database/migrations/2024_03_05_102941_create_user_settings_table.php
  database/migrations/2024_03_06_004152_create_achievements_table.php
  routes/api.php
Labels: ✨ Feature, 🔨 Refactor

#36 🔨 chore : gana 부분 배열이아닌 객체로 반환하는 오류 수정, swagger 작업 및 타자연습 route 주소 변경
  app/Helper/Helpers.php
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/ImageTranslationController.php
  app/Http/Controllers/TypingPracticeController.php
  app/Http/Controllers/VocabularyNoteController.php
  app/Models/Sentence.php
  composer.json
  composer.lock
  config/sanctum.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🐞 BugFix, 📃 Docs

#38 ✨ feat : vocabularyNote 수정, 삭제 개발
  app/Http/Controllers/CardController.php
  app/Http/Controllers/SocialController.php
  app/Http/Controllers/VocabularyNoteController.php
  app/Http/Controllers/WordOfWorldController.php
  app/Imports/VocabularyNoteImport.php
  app/Models/Sentence.php
  database/migrations/2024_02_29_070217_create_rankings_table.php
  database/migrations/2024_03_05_102941_create_user_settings_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feature

#40 ✨ feat : 타자연습 백엔드 구축 + swagger API 작업, 타자연습 route주소 변경
  app/Http/Controllers/TypingPracticeController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feature, 📃 Docs

#44 🔨 chore : ocr 최대 파일 w,h 초과시 w,h값 조정 로직 추가, 한자만 추출->히라가나도 같이 추출 변경
  .gitignore
  app/Helper/Helpers.php
  app/Http/Controllers/ImageTranslationController.php
  composer.json
  composer.lock
Labels: 🔨 Refactor

#46 ✨ feat : 출석체크 기능 개발, 🎨 refactor : 소셜 로그인 리팩토링
  app/Helper/Helpers.php
  app/Http/Controllers/CardController.php
  app/Http/Controllers/SocialController.php
  app/Http/Controllers/VocabularyNoteController.php
  app/Http/Controllers/WordOfWorldController.php
  app/Imports/VocabularyNoteImport.php
  app/Models/UserSetting.php
  app/Models/VocabularyNote.php
  composer.lock
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2024_02_27_064058_create_daily_checks_table.php
  database/migrations/2024_03_05_102941_create_user_settings_table.php
  docker/mysql/create-testing-database.sh
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feature, 🔨 Refactor

#48 🎨 refactor : ocr , papago 번역 기능 분리 및 내부 로직 수정
  app/Helper/Helpers.php
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/ImageTranslationController.php
  app/Http/Controllers/VocabularyNoteController.php
  composer.json
  composer.lock
  routes/api.php
  storage/api-docs/api-docs.json
Labels: 🔨 Refactor

#51 🔨 Refactor : token return 함수
  app/Helper/Helpers.php
  app/Http/Controllers/SocialController.php
  app/Http/Controllers/SpeechController.php
  app/Http/Controllers/VocabularyNoteController.php
  app/Service/AzureSpeechServicesApiClient.php
  config/services.php
  routes/api.php
Labels: 🔨 Refactor

#52 ✨ feat : testToken 생성로직 구현 및 Ocr 요청 로직 수정
  app/Helper/Helpers.php
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/TypingPracticeController.php
  app/Http/Controllers/VocabularyNoteController.php
  app/Http/Requests/UserRequest.php
  app/Models/DailyCheck.php
  config/services.php
  routes/api.php
Labels: ✨ Feature, 🔨 Refactor

#54 🐞 BugFix : 연속 출석 오류 수정
  app/Helper/Helpers.php
  app/Http/Controllers/SocialController.php
  app/Http/Controllers/SpeechController.php
  app/Models/DailyCheck.php
  app/Service/AzureSpeechServicesApiClient.php
  routes/api.php
Labels: 🐞 BugFix

#56 ✨ Feature : JLPT 문법 등급별 조회 기능 구현 및 JLPT 등급별 문법 생성 구현
  app/Helper/Helpers.php
  app/Http/Controllers/GrammarController.php
  app/Http/Controllers/VocabularyNoteController.php
  app/Models/Grammar.php
  database/migrations/2024_03_25_083445_create_grammars_table.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feature, 🔨 Refactor

#58 🐞 BugFix : 소셜로그인 함수 호출 에러 수정, 단어장 주소 설정 에러 수정
  app/Helper/Helpers.php
  app/Http/Controllers/SocialController.php
  app/Http/Controllers/VocabularyNoteController.php
Labels: 🐞 BugFix

#60 🐞 BugFix : response 에러
  app/Helper/Helpers.php
  app/Http/Controllers/GrammarController.php
  app/Http/Controllers/SocialController.php
  app/Http/Controllers/VocabularyNoteController.php
  app/Http/Controllers/WordOfWorldController.php
Labels: 🐞 BugFix

#62 🔨 Refactor : ocr mecab python 구현
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/VocabularyNoteController.php
  routes/api.php
  storage/api-docs/api-docs.json
Labels: ✨ Feature, 🔨 Refactor
